import "dotenv/config";

const WINSTON_APPLICATION_NAME = process.env.WINSTON_APPLICATION_NAME || "budget_api_log";
const WINSTON_DEFAULT_DATE_FORMAT = process.env.WINSTON_DEFAULT_DATE_FORMAT || "YYYY-MM-DD hh:mm:ss.SSS A";

const WINSTON_DEFAULT_LOG_LEVEL = process.env.WINSTON_DEFAULT_LOG_LEVEL || "http";
const WINSTON_DEFAULT_SEQ_URL = process.env.WINSTON_DEFAULT_SEQ_URL || "http://119.8.151.105/";
const WINSTON_DEFAULT_SEQ_API_KEY = process.env.WINSTON_DEFAULT_SEQ_API_KEY || "D0RySgVauhiQelKvflLN";

export {
    WINSTON_APPLICATION_NAME,
    WINSTON_DEFAULT_DATE_FORMAT,
    WINSTON_DEFAULT_SEQ_URL,
    WINSTON_DEFAULT_LOG_LEVEL,
    WINSTON_DEFAULT_SEQ_API_KEY
};